[theme]
primaryColor="#0077b6"
backgroundColor="#E2E8FB"
secondaryBackgroundColor="#79D0E6"
textColor="#000000"


# this is needed for local development with docker
[server]
# if you don't want to start the default browser:
headless = true
# you will need this for local development:
runOnSave = true
# you will need this if running docker on windows host:
fileWatcherType = "poll"

